services:
  backend:
    build: ./Backend #vai procurar um dockerfile pra compilar
    container_name: springboot-adotapet
    ports:
      - "8080:8080" #maquina:container
    volumes:
      - ./Backend:/app
    # environment:
    #   SPRING_APPLICATION_NAME: adotapet
    #   SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/adotapet
    #   SPRING_DATASOURCE_USERNAME: adotapet
    #   SPRING_DATASOURCE_PASSWORD: 1234
    #   SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
    #   SPRING_JPA_HIBERNATE_DDL_AUTO: update
    #   SPRING_JPA_SHOW_SQL: "true"
    #   SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQLDialect
  #frontend
  db:
    image: mariadb:10.4  # Ou mysql:5.7 se quiser MySQL puro
    container_name: mysql-xampp
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: adotapet
      MYSQL_USER: adotapet
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

  #comandos:
  #docker compose build